# Generated by Django 3.2.13 on 2022-05-11 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('borrow', 'borrow'), ('lend', 'lend')], max_length=10)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=10)),
                ('reason', models.TextField(default='')),
                ('transaction_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from', to=settings.AUTH_USER_MODEL)),
                ('transaction_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
