# Generated by Django 3.2.13 on 2022-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_amount',
            field=models.FloatField(default=0),
        ),
    ]
